version: '3'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile-python
    command: python3 src/test/e2e/test_array.py
    env_file:
      - docker-compose.env
    volumes:
      - .:/var/app:z
