version: "3"

services:

  selenium-hub:
    image: selenium/hub:3.14.0-dubnium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.14.0-dubnium
    depends_on:
      - selenium-hub
    env_file:
      - docker-compose.env
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    ports:
      - "5555:5555" 
